### ISSUE TITLE
Add ntlm.pw API

### ISSUE THREAD

**Issue by pinetest** [PaperMtn/lil-pwny#12]
Next to the HIBP api you could also add the NTLM.pw API to find pwnd passwords:

https://ntlm.pw/docs

**Comment by PaperMtn** [comment]
Thanks for the recommendation @pinetest.

I made a conscious decision when creating Lil Pwny that AD password hashes get processed 'on-device'. One of the main requirements was that hashes don't get sent to any third party. This is why Lil Pwny doesn't use the HIBP API, but rather checks hashes offline from the downloaded file. 

For that reason, this is something i'm not willing to implement.
